#ifndef GUARD_DEKSA_LEVEL_CAP_H
#define GUARD_DEKSA_LEVEL_CAP_H

#define DEKSA_PRE_BROCK_LEVEL_CAP 14
#define DEKSA_PRE_MISTY_LEVEL_CAP 21
#define DEKSA_PRE_SURGE_LEVEL_CAP 24
#define DEKSA_PRE_ERIKA_LEVEL_CAP 29
#define DEKSA_PRE_KOGA_SABRINA_LEVEL_CAP 43
#define DEKSA_PRE_BLAINE_LEVEL_CAP 47
#define DEKSA_PRE_GIOVANNI_LEVEL_CAP 50
#define DEKSA_PRE_LEAGUE_LEVEL_CAP 60
#define DEKSA_PRE_RUBY_LEVEL_CAP 65
#define DEKSA_PRE_SAPPHIRE_LEVEL_CAP 70
#define DEKSA_REMATCH_LEAGUE_LEVEL_CAP 75

u8 Deksa_GetLevelCap(void);

#endif // GUARD_DEKSA_LEVEL_CAP_H
